steps:
  # Step 1: Pull Docker Compose image
  # - name: 'docker/compose:1.29.2'
  #   entrypoint: 'sh'
  #   args:
  #     - '-c'
  #     - |
  #       docker-compose -f docker-compose.yml pull

  # Step 2: Build and push each service defined in your Docker Compose file
  - name: 'docker/compose:1.29.2'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push
        docker image ls

  # Optional: Run Docker Compose locally (if needed)
  # - name: 'docker/compose:1.29.2'
  #   entrypoint: 'sh'
  #   args:
  #     - '-c'
  #     - |
  #       docker-compose -f docker-compose.yml up -d
  #       docker image ls

  Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'saas-backend'  # Replace with your Cloud Run service name
      - '--image'
      - 'gcr.io/saas-boilerplate/saas/backend:$BUILD_ID'  # Replace with your image name
      - '--region'
      - 'us-central1'  # Replace with the region where you want to deploy
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

  # Cleanup: Stop and remove containers (optional if running locally)
  # - name: 'docker/compose:1.29.2'
  #   entrypoint: 'sh'
  #   args:
  #     - '-c'
  #     - |
  #       docker-compose -f docker-compose.yml down

serviceAccount: 'saas-445@saas-biolerplate.iam.gserviceaccount.com'
images:
  - 'gcr.io/saas-boilerplate/saas/backend:$BUILD_ID'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET