---
name: Build and Push Images to GCP

on:
    push:
        branches:
          - master
jobs:
    build-push-gcr:
        name: Build and Push to GCP
        runs-on: ubuntu-20.04
        steps:
            - name: checkout repository
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Set up Google Cloud SDK
              uses: google-github-actions/setup-gcloud@v2
              with:
                project_id: ${{ secrets.GCP_PROJECT_ID }}
                install_components: gcloud

            - name: Decode and Save Service Account Key
              run: |
                echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 --decode > $HOME/gcloud.json

            - name: Set GOOGLE_APPLICATION_CREDENTIALS
              run: echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json" >> $GITHUB_ENV

            - name: Log in to GCR
              run: |
                gcloud auth activate-service-account --key-file=$HOME/gcloud.json
                gcloud auth configure-docker --quiet

            - name: Build Docker images using Docker Compose
              run: docker compose -f docker-compose.yml build

            - name: Check created Docker Images
              run: docker image ls

            - name: Push Docker saas/backend image to Google Container Registry
              run:
                docker tag saas/backend:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/saas/backend:latest
                docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/saas/backend:latest

            - name: Push Docker saas-boilerplate-ssm-editor image to Google Container Registry
              run:
                docker tag saas-boilerplate-ssm-editor:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/saas-boilerplate-ssm-editor:latest
                docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/saas-boilerplate-ssm-editor:latest

            - name: Push Docker saas-boilerplate-workers image to Google Container Registry
              run:
                docker tag saas-boilerplate-workers:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/saas-boilerplate-workers:latest
                docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/saas-boilerplate-workers:latest
